### ISSUE TITLE
USER STORY: Update and delete a post

### ISSUE THREAD

**Issue by josemguerra** [JoseMGuerra/ci-pp4-django-fsf#12]
As a **Site User / Admin** I want be able to **update a post I created** so that **I can make changes or delete it**
## Acceptance Criteria:

- **Given** I am a registered user and I am in the post detail page
- **When** I click the update button i will be prompted to the update post page
- **Then** I can edit my post
- **And When** I click in the delete button and a confirmation modal will pop up
- **Then** I click delete and i will erase my post

## Tasks:

- [x]  Create an update view and template
- [x]  #25 Create a delete view and a modal
- [x]  Create a delete and an update button
