### ISSUE TITLE
USER STORY: Like / Unlike

### ISSUE THREAD

**Issue by josemguerra** [JoseMGuerra/ci-pp4-django-fsf#13]
As a **Site User** I want be able to **like or unlike a post** so that **I can interact with the content**

## Acceptance Criteria:

- **Given** I am a registered user
- **When** I click in the like icon 
- **Then** I can see the like icon change state and count increase or decrease

## Tasks:

- [x]  Add like field to model
- [x]  Add status like and unlike
- [x]  Map likes to User
