### ISSUE TITLE
USER STORY: Custom error pages

### ISSUE THREAD

**Issue by josemguerra** [JoseMGuerra/ci-pp4-django-fsf#33]
As a **Site Admin/ User** I want be able to  **have custom error pages with a return button** so that **I can return to the homepage if an error occurred**

## Tasks:

- [x]  Error handlers views
- [x] Error handlers url patterns
- [x]  Error templates for at least 403, 404, 405 and 500 error types
