### ISSUE TITLE
USER STORY: Comment on a post

### ISSUE THREAD

**Issue by josemguerra** [JoseMGuerra/ci-pp4-django-fsf#4]
As a **Site User** I want be able to **leave comments on a post** so that **I can be involved in the conversation**

## Acceptance Criteria:

- **Given** I am a registered user
- **When** I see a text box under the post
- **Then** I should be able to type a comment and click on post button and save it

## Tasks:

- [x]  Create a comment form
- [x]  Authorise only registered users superuser
- [x]  Hide post button if user is not registered
