### ISSUE TITLE
USER STORY: Update a comment

### ISSUE THREAD

**Issue by josemguerra** [JoseMGuerra/ci-pp4-django-fsf#5]
As a **Site User** I want be able to **update a comment I made** so that **I can make changes or delete a comment**

## Acceptance Criteria:

- **Given** I am the registered user who made the comment or superuser
- **When** I click in the  update button under the comment text box
- **Then** I will be able to edit my comment

## Tasks:

- [ ]  Add an update button to comment
- [ ]  Map comment with user
- [ ]  Prepopulate form with the comment to be edited
