### ISSUE TITLE
USER STORY: Profile picture to comments

### ISSUE THREAD

**Issue by josemguerra** [JoseMGuerra/ci-pp4-django-fsf#7]
As a **Site User** I want be able to **upload a profile picture** so that **I can see it  when I comment on a post**

## Acceptance Criteria:

- **Given** I am a registered user and am in my profile page
- **When** I see the upload file button and I click  on it 
- **Then** a window will pop up and I can pick a picture to upload

## Tasks:

- [x]  Add image field to profile form
- [x]  Update settings
- [x]  Set up Cloudinary or similar
- [ ]  Add profile picture to comments
